Add a new endpoint for new question assignment events
ibm-watson-data-lab/soslackbot pull request #1
Opened 2018-03-12 13:13 UTC by lornajane

When a POST request comes to `/stackoverflow/events` with the correct data format, let that user know that they have a question assigned to them.  Tricky to test since the test systems do not have genuine user IDs attached, I have this working locally apart from the user naming part and would appreciate some code review - bonus points if you can also run this locally!

To test:

Try a POST request: `curl -X POST -H "Content-Type: application/json" [path to your bot URL, can be localhost]/stackoverflow/events -d @data.json` with the `data.json` something like:

```
{
    "type": "assigned",
    "data": {
        "assigned_to": "U4",
        "assigned_to_name": "susie",
        "assigned_by": "U5",
        "assigned_by_name": "sarah",
        "question_id": "49232701",
        "title": "Compare 2 dates in a symfony form with mapped = false"
    }
}
```

2018-03-12 19:52 UTC, terichadbourne requested changes
This is working for me after some readme clarification on how to run it locally. 

Two quick suggestions for improvement: 
1. Change "this" to "the" in the Slack message produced. 
2. Provide a more helpful 400 error message, perhaps by adding a URL for documentation.

2018-03-13 00:26 UTC, rajrsingh commented
Here's one installation hurdle. There's a package only supported by Python 2.x: 
> `gyp ERR! stack Error: Python executable "/Users/rajrsingh/anaconda3/bin/python" is v3.6.3, which is not supported by gyp.`

2018-03-13 10:03 UTC, lornajane commented
I'm really unclear what the gyp thing is, I know I fixed it some time ago on my mac for another project and it doesn't seem to occur on other platforms.  @teri I think you ran into this, can you help us unblock @rajrsingh ?  This should probably be in the readme since a couple of people have encountered it.

2018-03-13 14:22 UTC, terichadbourne commented
This is what I saw on my first attempt at `npm install `of this project yesterday. For me there were no warnings about Python, which is something I haven't intentionally installed. Maybe Raj's Python is *too* up-to-date?? For me I had to update Node and install XCode, but not do anything directly about gyp. If the problems are happening because we all have different things on our laptops, then maybe the dependencies aren't listed correctly in the package.json? I'm definitely not equipped to help fix this one. Sorry!

![image](https://user-images.githubusercontent.com/19171465/37347356-06bcb006-26a8-11e8-9c22-c3c66a8475b1.png)

2018-03-13 22:40 UTC, isc-rsingh commented
The Python version didn't block me @lornajane. I activated my Python 2.x anaconda enviroment, ran `npm install`, then went back to my Python 3 environment. It was a hurdle but not a blocker. My blocker is getting the slack bot API token.

2018-03-15 11:17 UTC, lornajane commented
Thanks @teri - I've tweaked the wording on the message.  I've opened a ticket to improve the error message - right now the bot is open to the world so I think I should probably fix that first before providing instructions on how people can abuse the bot to send nonsense into the channel if that's OK.  With the issue open though, it won't get forgotten.  Let me know if you think we're getting closer to being ready with this.

2018-03-16 14:12 UTC, terichadbourne approved these changes
Looks good to me!

2018-03-16 15:01 UTC, terichadbourne commented
This isn't actually working for me anymore. 

When I run curl I get this: 
    curl: (6) Could not resolve host: application
    This endpoint expects a specific data structure; see docs

I've confirmed the message is coming from the function that starts: 
    express_webserver.post('/stackoverflow/event', function(req, res) {

I added some console logs at the start of that function like this: 
        console.log("req.body: " + req.body);
        console.log("req.body.data: " + req.body.data);
        console.log("typeof req.body.data: " + typeof req.body.data);
        console.log("req.body.data.title: " + req.body.data.title);

Which result in this when i run curl: 
    req.body: [object Object]
    req.body.data: undefined
    typeof req.body.data: undefined
    TypeError: Cannot read property 'title' of undefined

Just flailing at this point so leaving this for Lorna to look at later.

2018-05-02 08:12 UTC, closed without merging